# Solving Sudoku Puzzles
## Assignment Preamble
Please ensure you carefully read all of the details and instructions on the assignment page, this section, and the rest of the notebook. If anything is unclear at any time please post on the forum or ask a tutor well in advance of the assignment deadline.

In addition to all of the instructions in the body of the assignment below, you must also follow the following technical instructions for all assignments in this unit. *Failure to do so may result in a grade of zero.*
* [At the bottom of the page](#Submission-Test) is some code which checks you meet the submission requirements. You **must** ensure that this runs correctly before submission.
* Do not modify or delete any of the cells that are marked as test cells, even if they appear to be empty.
* Do not duplicate any cells in the notebook – this can break the marking script. Instead, insert a new cell (e.g. from the menu) and copy across any contents as necessary.

Remember to save and backup your work regularly, and double-check you are submitting the correct version.

This notebook is the primary reference for your submission. You may write code in separate `.py` files but it must be clearly imported into the notebook so that it runs without needing to reference those files, and you must explain clearly what functionality is contained in those files (through comments, markdown cells, etc).

As always, **the work you submit for this assignment must be entirely your own.** Do not copy or work with other students. Do not copy answers that you find online. These assignments are designed to help improve your understanding first and foremost – the process of doing the assignment is part of *learning*. They are also used to assess your ability, and so you must uphold academic integrity. Submitting plagiarised work risks your entire place on your degree.

**You must implement your own work.** You can and are encouraged to use helper libraries like `numpy`, but you must not use 3rd-party libraries or code that solves the assignment for you. *Even if it is properly referenced*, you only get marks for work you have done. If you are unsure, ask on the forum or ask a tutor directly.

**The pass mark for this assignment is 40%.** We expect that students, on average, will be able to produce a submission which gets a mark between 50-70% within the normal workload allocation for the unit, but this will vary depending on individual backgrounds. Please ask for help if you are struggling.

## Getting Started
For this assignment, you will be writing an agent that can solve sudoku puzzles. You should be familiar with sudoku puzzles from the unit material. You are given a 9x9 grid with some fixed values. To solve the puzzle, the objective is to fill the empty cells of the grid such that the numbers 1 to 9 appear exactly once in each row, column, and 3x3 block of the grid. 

Below is a sample puzzle along with its solution. 

<img src="images/sudoku.png" style="width: 50%;"/>

For this assignment you will need to submit:
1. The implementation for an agent which can solve sudoku puzzles – this notebook
 * You can use any algorithm you like, from the unit material or otherwise
 * Your code will be subject to automated testing, from which grades will be assigned based on whether it can solve sudokus of varying difficulty
 * To get a high grade on this assignment, the speed of your code will also be a factor – the quicker the better
 * There are some sample tests included below, make sure your code is compatible with the format of these tests
2. A text file that explains your approach and the decisions you made in your own words – a readme file
 * Submissions that do not include the written section will receive zero marks – **this part is mandatory**
 * You may write your file in plain text (.txt) or [Markdown](https://www.markdownguide.org/basic-syntax/) (.md)
 * To get top marks on this assignment, as well as getting a high grade from your implementation, you must also demonstrate excellent academic presentation in your written section

### Choice of Algorithm
The choice of algorithm to solve sudoku puzzles is up to you. We expect you will use search techniques from the unit, but you could make something up yourself, or do some independent research to find something else. You will need to evaluate and balance the trade-off between how well suited you think the algorithm is and how difficult it is to write, but there is some advice below.

You should also consider what *data structures* you use within your code. Certain algorithms will work much faster with certain data structures, and understanding this is considered part of understanding the algorithm itself. 

I suggest you implement *constraint satisfaction* as it is described in the unit material. A good implementation of a backtracking depth-first search with constraint propagation should be sufficient to get a good grade in the automated tests (roughly 60-70%). There is an example of constraint satisfaction on the eight-queens puzzle, and you could use this as a guide to help you get started.

You could also write a successful agent that uses the other search techniques you have seen in the unit so far: basic search, heuristic search, or local search. You may find these easier to implement, though they may perform less well. 

To get a high grade on this assignment will require a particularly efficient implementation of constraint satisfaction, or something which goes beyond the material we have presented. *This is left unguided and is not factored into the unit workload estimates.*

If you choose to implement more than one algorithm, please feel free to include your code and write about it in part two (readme file), but only the code in this notebook will be used in the automated testing.

## Sample Sudoku Puzzles
To get started, the cell below will load in some sample sudoku puzzles for you so you can see the format. There are sudokus provided of multiple difficulties (easier sudokus typically start with more digits provided). The cell below only loads the easiest, but there is another test cell lower in the notebook which will run your code against all of the provided puzzles.

Each sudoku is a 9x9 NumPy array of integers, where zero represents an empty square. Each difficulty comes with 15 sudokus, so when you load the file, it is stored in a 15x9x9 array.

In [1]:
import numpy as np

# Load sudokus
sudoku = np.load("data/very_easy_puzzle.npy")
print("very_easy_puzzle.npy has been loaded into the variable sudoku")
print(f"sudoku.shape: {sudoku.shape}, sudoku[0].shape: {sudoku[0].shape}, sudoku.dtype: {sudoku.dtype}")

# Load solutions for demonstration
solutions = np.load("data/very_easy_solution.npy")
print()

# Print the first 9x9 sudoku...
print("First sudoku:")
print(sudoku[0], "\n")

# ...and its solution
print("Solution of first sudoku:")
print(solutions[0])

very_easy_puzzle.npy has been loaded into the variable sudoku
sudoku.shape: (15, 9, 9), sudoku[0].shape: (9, 9), sudoku.dtype: int8

First sudoku:
[[1 0 4 3 8 2 9 5 6]
 [2 0 5 4 6 7 1 3 8]
 [3 8 6 9 5 1 4 0 2]
 [4 6 1 5 2 3 8 9 7]
 [7 3 8 1 4 9 6 2 5]
 [9 5 2 8 7 6 3 1 4]
 [5 2 9 6 3 4 7 8 1]
 [6 0 7 2 9 8 5 4 3]
 [8 4 3 0 1 5 2 6 9]] 

Solution of first sudoku:
[[1 7 4 3 8 2 9 5 6]
 [2 9 5 4 6 7 1 3 8]
 [3 8 6 9 5 1 4 7 2]
 [4 6 1 5 2 3 8 9 7]
 [7 3 8 1 4 9 6 2 5]
 [9 5 2 8 7 6 3 1 4]
 [5 2 9 6 3 4 7 8 1]
 [6 1 7 2 9 8 5 4 3]
 [8 4 3 7 1 5 2 6 9]]


## Part One
You should write all of your code for solving sudokus below this cell.

You must include a function called `sudoku_solver(sudoku)` which takes one sudoku puzzle (a 9x9 NumPy array) as input, and returns the solved sudoku as another 9x9 NumPy array. This is the function which will be tested. 

In [2]:
import numpy as np
# will be re-imported just in case


# a way of checking if we completed the grid (assuming all rules followed)
def is_solved(sudoku):
    if np.sum(sudoku) == 405:
        return True
    return False


# generate index of cells with zeros
def get_zeros(sudoku):
    zeros_index = [(y, x) for y in range(9) for x in range(9) if sudoku[y][x] == 0]
    return zeros_index


# generate index of cells with zeros
def clues(sudoku):
    val = (81 - len(get_zeros(sudoku)))
    return val


# generate an optimised start sequence for backtracking
def get_zeros_backtrack(sudoku):
    # all code only sequences the cells in row-sequence and col-sequence
    # for some reason using col-sequence slowed down those cases slightly
    # could be due to the way numpy-arrays are addressed
    # or the slow down from generating the index itself.
    if clues(sudoku) > 26:  # it is a fudge value - 26 and it almost doesn't matter
        row_list = [0] * 9
        for row_n, row in enumerate(sudoku):
            for cell in row:
                if cell != 0:
                    row_list[row_n] += 1

        max_value_r = max(row_list)
        max_index1 = row_list.index(max_value_r)

        zeros_index1 = [(y, x) for y in range(max_index1, 9) for x in range(9) if sudoku[y][x] == 0]
        zeros_index2 = [(y, x) for y in range(max_index1) for x in range(9) if sudoku[y][x] == 0]

        zero_index = zeros_index1 + zeros_index2

    else:
        zero_index = get_zeros(sudoku)
    return zero_index


# solve the most obvious cells
def solve_for_options(options, sudoku):
    for k in options:
        if len(options[k]) == 1:
            sudoku[k] = options[k][0]
    return sudoku


# List1 - remove (to avoid set conversion)
def naked_helper(list1, remove):
    result = [value for value in list1 if value not in remove]
    return result


# Hidden singles
def hidden_singles(sudoku):
    zeros = get_zeros(sudoku)
    options = get_options(sudoku)
    for (y_pos, x_pos) in zeros:
        option = options[(y_pos, x_pos)]
        for col in [r for r in range(9) if r != x_pos]:
            if (y_pos, col) in options:
                d = options[(y_pos, col)]
                option = naked_helper(option, d)
            if len(option) < 1:
                break
        if len(option) == 1:
            # it could be this value will violates other cells (like hard 15)
            if is_move_valid(sudoku, y_pos, x_pos, option[0]):
                sudoku[(y_pos, x_pos)] = option[0]
            else:
                return -1 * np.ones_like(sudoku)

    zeros = get_zeros(sudoku)
    for (y_pos, x_pos) in zeros:
        option = options[(y_pos, x_pos)]
        for row in [r for r in range(9) if r != y_pos]:
            if (row, x_pos) in options:
                d = options[(row, x_pos)]
                option = naked_helper(option, d)
        if len(option) == 1:
            # it could be this value will violates other cells (like hard 15)
            if is_move_valid(sudoku, y_pos, x_pos, option[0]):
                sudoku[(y_pos, x_pos)] = option[0]
            else:
                return -1 * np.ones_like(sudoku)

    zeros = get_zeros(sudoku)
    for (y_pos, x_pos) in zeros:
        option = options[(y_pos, x_pos)]
        sub_cell_y = (y_pos // 3) * 3
        sub_cell_x = (x_pos // 3) * 3
        for y in range(sub_cell_y, sub_cell_y + 3):
            for x in range(sub_cell_x, sub_cell_x + 3):
                if x == x_pos and y == y_pos:
                    continue
                elif (y, x) in options:
                    d = options[(y, x)]
                    option = naked_helper(option, d)
        if len(option) == 1:
            # it could be this value will violates other cells (like hard 15)
            if is_move_valid(sudoku, y_pos, x_pos, option[0]):
                sudoku[(y_pos, x_pos)] = option[0]
            else:
                return -1 * np.ones_like(sudoku)
    return sudoku


# an options dict of each cell (for validation check of the board validity - as solvable)
def get_options_full(sudoku):
    options = hidden_pairs(sudoku)  # this is the most robust way of detecting a defective game
    for y in range(9):
        for x in range(9):
            if sudoku[y][x] != 0:
                options[(y, x)] = []
    return options


# an options dict of each 0 cell
def get_options(sudoku):
    zeros = get_zeros(sudoku)
    options = {}
    for (y, x) in zeros:
        options[(y, x)] = [opt for opt in range(1, 10) if is_move_valid(sudoku, y, x, opt)]
    return options


# search and remove based on naked pairs (in rows, cols, boxes)
def get_options_nkd_pairs(sudoku):
    options = get_options(sudoku)
    # converted to set equations (mostly) - no major speed difference, probably due to the mix of lists and sets
    sub_sets = [{1, 2}, {1, 3}, {1, 4}, {1, 5}, {1, 6}, {1, 7}, {1, 8}, {1, 9},
                {2, 3}, {2, 4}, {2, 5}, {2, 6}, {2, 7}, {2, 8}, {2, 9}, {3, 4}, {3, 5}, {3, 6}, {3, 7}, {3, 8}, {3, 9},
                {4, 5}, {4, 6}, {4, 7}, {4, 8}, {4, 9}, {5, 6}, {5, 7}, {5, 8}, {5, 9}, {6, 7}, {6, 8}, {6, 9}, {7, 8},
                {7, 9}, {8, 9}]
    
    for sub_set in sub_sets:
        for row in range(9):
            location = []    
            for col in range(9):
                if (row, col) in options:
                    if set(options[(row, col)]) == sub_set:
                        location.append((row, col))
                if len(location) == 2:
                    for col2 in range(9):
                        if (row, col2) in options and (row, col2) not in location:
                            options[(row, col2)] = naked_helper(options[(row, col2)], list(sub_set))

    for sub_set in sub_sets:
        for col in range(9):
            location = []    
            for row in range(9):
                if (row, col) in options:
                    if set(options[(row, col)]) == sub_set:
                        location.append((row, col))
                if len(location) == 2:
                    for row2 in range(9):
                        if (row2, col) in options and (row2, col) not in location:
                            options[(row2, col)] = naked_helper(options[(row2, col)], list(sub_set))

    # still old for-loop based value comparison
    for sub_set in sub_sets:
        for row in [0, 3, 6]:
            for col in [0, 3, 6]:
                location = []
                for y in range(row, row + 3):
                    for x in range(col, col + 3):
                        if (y, x) in options:
                            if set(options[(y, x)]) == sub_set:
                                location.append((y, x))
                        if len(location) == 2:
                            for y2 in range(row, row + 3):
                                for x2 in range(col, col + 3):
                                    if (y2, x2) in options and (y2, x2) not in location:
                                        options[(y2, x2)] = naked_helper(options[(y2, x2)], list(sub_set))
    return options


def hidden_pairs(sudoku):
    options = get_options_nkd_pairs(sudoku)
    sub_sets = [{1, 2}, {1, 3}, {1, 4}, {1, 5}, {1, 6}, {1, 7}, {1, 8}, {1, 9},
                {2, 3}, {2, 4}, {2, 5}, {2, 6}, {2, 7}, {2, 8}, {2, 9}, {3, 4}, {3, 5}, {3, 6}, {3, 7}, {3, 8}, {3, 9},
                {4, 5}, {4, 6}, {4, 7}, {4, 8}, {4, 9}, {5, 6}, {5, 7}, {5, 8}, {5, 9}, {6, 7}, {6, 8}, {6, 9}, {7, 8},
                {7, 9}, {8, 9}]

    # hidden pairs for row
    for y in range(9):
        location = []
        for sub_set in sub_sets:
            count = 0
            tmp = []
            for x in range(9):
                if (y, x) not in options:
                    continue
                unit = options[(y, x)]
                if sub_set.issubset(unit):
                    count += 1
                    tmp.append((y, x))
            if count == 2:
                location.append((sub_set, tmp[0], tmp[1]))
                tmp.clear()

        for (digits, loc1, loc2) in location:
            found_first = 0
            for digit_number in (list(digits)):
                count2 = 0
                single_digit = {digit_number}
                for x in range(9):
                    if (y, x) not in options:
                        continue
                    unit2 = options[(y, x)]
                    if single_digit.issubset(unit2):
                        if (y, x) != loc1 and (y, x) != loc2:
                            count2 = 0
                            found_first = 0
                            break
                        else:
                            count2 += 1
                if count2 == 2 and found_first != 1:
                    found_first += 1
                elif count2 == 2 and found_first == 1:
                    options[loc1] = list(digits)
                    options[loc2] = list(digits)


# hidden pairs for columns
    for x in range(9):
        location2 = []
        for sub_set in sub_sets:
            count = 0
            tmp = []
            for y in range(9):
                if (y, x) not in options:
                    continue
                unit = options[(y, x)]
                if sub_set.issubset(unit):
                    count += 1
                    tmp.append((y, x))
            if count == 2:
                location2.append((sub_set, tmp[0], tmp[1]))
                tmp.clear()

        for (digits, loc1, loc2) in location2:
            found_first = 0
            for digit_number in (list(digits)):
                count2 = 0
                single_digit = {digit_number}
                for y in range(9):
                    if (y, x) not in options:
                        continue
                    unit2 = options[(y, x)]
                    if single_digit.issubset(unit2):
                        if (y, x) != loc1 and (y, x) != loc2:
                            count2 = 0
                            found_first = 0
                            break
                        else:
                            count2 += 1
                if count2 == 2 and found_first != 1:
                    found_first += 1
                elif count2 == 2 and found_first == 1:
                    options[loc1] = list(digits)
                    options[loc2] = list(digits)
    
    # hidden pairs for boxes
    for row in [0, 3, 6]:
        for col in [0, 3, 6]:
            location3 = []
            for sub_set in sub_sets:
                count = 0
                tmp = []
                for y in range(row, row + 3):
                    for x in range(col, col + 3):
                        if (y, x) in options:
                            unit = options[(y, x)]
                            if sub_set.issubset(unit):
                                count += 1
                                tmp.append((y, x))
                if count == 2:
                    location3.append((sub_set, tmp[0], tmp[1]))        
                    tmp.clear()
                        
            for (digits, loc1, loc2) in location3:
                found_first = 0
                for digit_number in (list(digits)):
                    count2 = 0
                    single_digit = {digit_number}
                    skip = 0
                    for y in range(row, row + 3):
                        for x in range(col, col + 3):
                            if (y, x) in options and skip == 0:
                                unit2 = options[(y, x)]
                                if single_digit.issubset(unit2):
                                    if (y, x) != loc1 and (y, x) != loc2:
                                        count2 = 0
                                        found_first = 0
                                        skip = 1
                                    else:
                                        count2 += 1
                    if count2 == 2 and found_first != 1:
                        found_first += 1
                    elif count2 == 2 and found_first == 1:
                        options[loc1] = list(digits)
                        options[loc2] = list(digits)
    
    return options


def check_valid_state(sudoku):
    options = get_options_full(sudoku)

    # element_row
    rows_set = []
    for y in range(9):
        tmp_index = [(y, x) for x in range(9)]
        rows_set.append(tmp_index)

    # element_col
    cols_set = []
    for x in range(9):
        tmp_index = [(y, x) for y in range(9)]
        cols_set.append(tmp_index)

    # check rows and columns
    for row_col_set in [rows_set, cols_set]:
        for index in row_col_set:
            check_list = [sudoku[y][x] for y, x in index]

            # check that they are all containing at max a single entry of each value
            if not all_single_qty(check_list):
                return False

            # check that within the compliant options, it possible to generate a valid result
            range_cells = (index[0], index[len(index) - 1])
            check_list += list(scan_options(options, range_cells))
            possible = all_available(check_list)
            if not possible:
                return False

    # check boxes
    for y0 in [0, 3, 6]:
        for x0 in [0, 3, 6]:
            sub_box = []
            for y in range(y0, y0 + 3):
                for x in range(x0, x0 + 3):
                    sub_box.append(sudoku[y, x])
                    # all the values of a sub-box
            if not all_single_qty(sub_box):
                return False

            for y in range(y0, y0 + 3):
                for x in range(x0, x0 + 3):
                    full_opt = set(options[y, x])
                    sub_box += full_opt
                    # sum sudoku values and options
            possible = all_available(sub_box)
            if not possible:
                return False
    return True


# uses the get_options to check all options ina  given row/col/box
def scan_options(options, range_cells):
    # modified to not use sudoku but directly take the options list
    # using sets to easily get the set union
    # and performs the union with each cell in an rcb
    first_cell, last_cell = range_cells
    scanned = set()
    
    for y in range(first_cell[0], last_cell[0] + 1):
        for x in range(first_cell[1], last_cell[1] + 1):
            sub_opt = set(options[y, x])
            scanned = scanned | sub_opt
    return scanned


# confirm only 1 input per value in rcb (row/col/box)
def all_single_qty(rcb):
    qty = count_hits(rcb)
    for max_n in qty:  # exclude 0:
        if max_n > 1:
            return False  # more than 1 of value
    return True


# confirm all values are available in rcb (row/col/box)
def all_available(rcb):
    qty = count_hits(rcb)
    for min_n in qty:  # exclude 0:
        if min_n == 0:
            return False
    return True


# used by all_available() and all_single_qty()
def count_hits(rcb):
    qty = [0] * 9
    for value in rcb:
        if value > 0:  # no need to check for 0
            qty[value - 1] += 1  # if we see 1, save in pos 0, if we see 9, save in pos 8
    return qty


# most basic algo - used to generate zeros - initially used to validate back-tracking guess
def is_move_valid(sudoku, y, x, possible):
    for index in range(9):
        if (sudoku[y][index] == possible) or (sudoku[index][x] == possible):
            return False
    sub_cell_y = (y // 3) * 3
    sub_cell_x = (x // 3) * 3
    for y in range(sub_cell_y, sub_cell_y + 3):
        for x in range(sub_cell_x, sub_cell_x + 3):
            if sudoku[y][x] == possible:
                return False
    return True


def back_tracker(valid_options, zeros, sudoku):
    for (y_pos, x_pos) in zeros:
        valid_values = valid_options[(y_pos, x_pos)]
        if len(valid_values) < 1:  # invalid grid if there is no option (not necessary probably)
            return sudoku
        for possible in valid_values:
            # theoretically we can delete some options, but it is slow to re-build the options list
            if is_move_valid(sudoku, y_pos, x_pos, possible):
                sudoku[y_pos, x_pos] = possible
                dump, *new_zeros = zeros
                sudoku = back_tracker(valid_options, new_zeros, sudoku)
                if not is_solved(sudoku):
                    sudoku[y_pos, x_pos] = 0
                else:
                    break
        break
    return sudoku


# main wrapper function
def sudoku_solver(sudoku):
    # same like -1 * np.ones_like(sudoku)
    failed = np.array([
                    [-1, -1, -1, -1, -1, -1, -1, -1, -1],
                    [-1, -1, -1, -1, -1, -1, -1, -1, -1],
                    [-1, -1, -1, -1, -1, -1, -1, -1, -1],
                    [-1, -1, -1, -1, -1, -1, -1, -1, -1],
                    [-1, -1, -1, -1, -1, -1, -1, -1, -1],
                    [-1, -1, -1, -1, -1, -1, -1, -1, -1],
                    [-1, -1, -1, -1, -1, -1, -1, -1, -1],
                    [-1, -1, -1, -1, -1, -1, -1, -1, -1],
                    [-1, -1, -1, -1, -1, -1, -1, -1, -1]
                    ])

    sudoku = hidden_singles(sudoku)
    loop_flag = True
    while loop_flag:
        start = sudoku.copy()
        sudoku = hidden_singles(sudoku)
        options = get_options_nkd_pairs(sudoku)
        sudoku = solve_for_options(options, sudoku)
        finish = sudoku.copy()
        if np.array_equal(start, finish): # check if it is worth to loop again (may cause 1 extra redundant loop)
            loop_flag = False
    if not check_valid_state(sudoku):  # check if it is simply not solvable
        return failed
    elif is_solved(sudoku):
        return sudoku
    options = hidden_pairs(sudoku)  # use the least options for back-tracking
    zeros = get_zeros_backtrack(sudoku)  # use the least options for back-tracking
    sudoku = back_tracker(options, zeros, sudoku)
    if not is_solved(sudoku):
        return failed
    return sudoku

All of your code must go above this cell. You may add additional cells into the notebook if you wish, but do not duplicate or copy/paste cells as this can interfere with the grading script.

### Testing Details
There are four difficulties of sudoku provided: very easy, easy, medium, and hard. There are 15 sample sudokus in each category, with solutions as well. Difficulty was determined using reference solvers, but your code may vary; it is conceivable that your code will find some sudokus much easier or harder within a given category, or even between categories.

*All categories that are easy and above will contain* ***invalid initial states***, that is, sudoku puzzles with no solution. In this case, your function should return a 9x9 NumPy array whose values are all equal to -1.

When we test your code, we will firstly test it on the *same* very easy puzzles that you have been given. Then we will test it on additional *hidden* sudokus from each difficulty in turn, easy and up – many more than 15 of each. Grades are awarded based on whether your code can solve the puzzles. For high grades on the hard puzzles, execution time will also be a factor. 

All puzzles must take under 20 seconds each on the test machine to count as successful – if it takes longer, it will timeout. Note that this is a maximum, not a goal. Higher grades require better performance on harder puzzles. As a very rough benchmark, you should be aiming for an average of under a second per puzzle. Hardware varies, but all tests will take place on the same modern desktop machine. Our ‘standard constraint satisfaction’ implementation takes about 0.001 seconds per puzzle for the very easy category, but struggles to solve some of the hard puzzles within the time limit.

***The hard sudokus are labelled as hard for a reason.*** We expect most submissions will not be able to solve them in a reasonable length of time. Use the stop button (■) on the toolbar if you need to terminate your code because it is taking too long.

The best way to improve the performance of your code is through a detailed understanding and smart choice of AI algorithms and data structures. This assignment is ***not*** meant to test your ability to write multi-threaded code or any other kind of high-performance code optimisations. 

#### Test Cell
The following code will run your solution over the provided sudoku puzzles. To enable it, set the constant `SKIP_TESTS` to `False`. If you fail any tests of one difficulty, the code will stop, but you can modify this behaviour if you like.

**IMPORTANT**: you must set `SKIP_TESTS` back to `True` before submitting this file!

In [1]:
SKIP_TESTS = True

def tests():
    import time
    difficulties = ['very_easy', 'easy', 'medium', 'hard']

    for difficulty in difficulties:
        print(f"Testing {difficulty} sudokus")
        
        sudokus = np.load(f"data/{difficulty}_puzzle.npy")
        solutions = np.load(f"data/{difficulty}_solution.npy")
        
        count = 0
        for i in range(len(sudokus)):
            sudoku = sudokus[i].copy()
            print(f"This is {difficulty} sudoku number", i)
            print(sudoku)
            
            start_time = time.process_time()
            your_solution = sudoku_solver(sudoku)
            end_time = time.process_time()
            
            print(f"This is your solution for {difficulty} sudoku number", i)
            print(your_solution)
            
            print("Is your solution correct?")
            if np.array_equal(your_solution, solutions[i]):
                print("Yes! Correct solution.")
                count += 1
            else:
                print("No, the correct solution is:")
                print(solutions[i])
            
            print("This sudoku took", end_time-start_time, "seconds to solve.\n")

        print(f"{count}/{len(sudokus)} {difficulty} sudokus correct")
        if count < len(sudokus):
            break
            
if not SKIP_TESTS:
    tests()

## Submission Test
The following cell tests if your notebook is ready for submission. **You must not skip this step!**

Restart the kernel and run the entire notebook (Kernel → Restart & Run All). Now look at the output of the cell below. 

*If there is no output, then your submission is not ready.* Either your code is still running (did you forget to skip tests?) or it caused an error.

As previously mentioned, failing to follow these instructions can result in a grade of zero.

In [2]:
def submission_tests():
    import sys
    import pathlib

    fail = False;

    if not SKIP_TESTS:
        fail = True;
        print("You must set the SKIP_TESTS constant to True in the cell above.")

    p1 = pathlib.Path('./readme.txt')
    p2 = pathlib.Path('./readme.md')
    if not (p1.is_file() or p2.is_file()):
        fail = True;
        print("You must include a separate file called readme.txt or readme.md in your submission.")

    p3 = pathlib.Path('./sudoku.ipynb')
    if not p3.is_file():
        fail = True
        print("This notebook file must be named sudoku.ipynb")

    if "sudoku_solver" not in globals():
        fail = True;
        print("You must include a function called sudoku_solver which accepts a numpy array.")
    else: 
        sudoku = np.load("data/very_easy_puzzle.npy")[0]
        solution = np.load("data/very_easy_solution.npy")[0]

        if not np.array_equal(sudoku_solver(sudoku), solution):
            print("Warning:")
            print("Your sudoku_solver function does not correctly solve the first sudoku.")
            print()
            print("Your assignment is unlikely to get any marks from the autograder. While we will")
            print("try to check it manually to assign some partial credit, we encourage you to ask")
            print("for help on the forum or directly to a tutor.")
            print()
            print("Please use the readme file to explain your code anyway.")

    if fail:
        print()
        sys.stderr.write("Your submission is not ready! Please read and follow the instructions above.")
    else:
        print("All checks passed. When you are ready to submit, upload the notebook and readme file to the")
        print("assignment page, without changing any filenames.")
        print()
        print("If you need to submit multiple files, you can archive them in a .zip file. (No other format.)")
        
submission_tests()

You must include a function called sudoku_solver which accepts a numpy array.



Your submission is not ready! Please read and follow the instructions above.

In [5]:
# This is a TEST CELL. Do not delete or change.